### PR TITLE
Fixed deterministic monad replay bug, and made quality of life changes.

### PR DESCRIPTION
**Pull request by aaditmshah**
One of the problems with your current implementation of the `immutagen` function is that it always creates and replays a new generator every time you call the `next` method. Due to this behavior, even deterministic monads are replayed multiple times. Consider the following example.

```
Welcome to Node.js v12.0.0.
Type ".help" for more information.
> const immutagen = require("immutagen").default;
undefined
> const foo = immutagen(function* () {
... console.log("a");
... yield 1;
... console.log("b");
... yield 2;
... console.log("c");
... return 3;
... });
undefined
> foo().next().next()
a
a
b
a
b
c
{ value: 3, next: undefined, mutable: Object [Generator] {} }
```

As you can see the expected output is `a b c` but the actual output is `a a b a b c`. I fixed this bug by only creating and replaying a new generator when the `next` method is called more than once. On the first call, it returns the current generator. This also improves the run time of non-deterministic monads.

In addition, I rewrote your code in a style which I believe is more readable and understandable. I also exported `immutagen` as both a named export and a default export. Hence, you can import it as `import immutagen from "immutagen"` in ES modules, and as `const {immutagen} = require("immutagen");` in node modules.

Finally, I made some quality of life changes:

1. I updated all the `devDependencies` to their latest versions. This fixed the security vulnerabilities that `npm audit` revealed.
2. I removed the generated `immutable.js` build file from the git repository. However, I added an npm `prepare` script ([info](https://docs.npmjs.com/misc/scripts)) which automatically runs the tests and generates the build file whenever you execute `npm publish` or `npm install` (without arguments). Hence, your build file will still be a part of your npm package even though it's now in `.gitignore`.
3. I removed the `yarn.lock` file and added the `package-lock.json` file. Now that npm can do everything that yarn does, there's no need to use yarn. However, if you want you can simply restore the file from a previous commit.

So, those are all the changes I made. You should execute `npm run release:patch` after merging this pull request so that the fix for the deterministic monad replay bug will be deployed.

P.S. I added myself as a contributor to this package in the `package.json` file.

### CODE REVIEW

**Comment by pelotom** [comment]
Looks good, thanks!

**Comment by pelotom** [comment]
Tried running the release but hit this:

```
> npm run release:patch

> immutagen@1.0.8 release:patch /Users/tom/code/immutagen
> xyz --increment patch

/Users/tom/code/immutagen/node_modules/.bin/xyz: line 125: branch: unbound variable
```

Not sure what that's about and I don't really have time to investigate, but I added you as a collaborator.

**Comment by aaditmshah** [comment]
I fixed the bug in 2ec787c. The problem was a lodash vulnerability. Hence, I updated lodash. I also ran the `npm run release:patch` command and it created and pushed a new `v1.0.9` release. However, because I don't have the permission to publish `immutagen` on npm, the last step failed. You'll have to publish the latest version yourself by running the following command after pulling the latest changes.

```bash
env VERSION=1.0.9 PREVIOUS_VERSION=1.0.8 bash -c 'npm publish'
```

By the way, thank you for creating this amazing package.

**Comment by aaditmshah** [comment]
By the way, make sure that you run `npm install` before publishing. This is to ensure that you build the top level `immutable.js` file which needs to be published.

**Edit:** Actually, it shouldn't matter because the`prepare` script that I added should be executed when you run `npm publish` but before actually publishing.

**Comment by pelotom** [comment]
>However, because I don't have the permission to publish `immutagen` on npm, the last step failed. 

I'm happy to make you a maintainer on NPM as well, what's your username?

> By the way, thank you for creating this amazing package.

Thank you for making it better!

**Comment by aaditmshah** [comment]
My username on NPM is `aaditmshah`.

**Comment by pelotom** [comment]
K, added you.

**Pull request merged**
